name: device-hub

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    # https://github.com/marketplace/actions/golangci-lint#annotations
    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: check license headers
        env:
          CI_COMPONENTS_PATH: ci-components
          PROJECT_PATH: .
        shell: bash
        run: |
          ci-components/scripts/fmt/check_license.sh

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          only-new-issues: true
          args: ./...

      - name: verify dependencies
        shell: bash
        run: |
          go mod download
          go mod tidy

          if [ -n "$(git status --porcelain .)" ]; then
            echo "Please run 'go mod tidy' and commit the updated files."
            exit 1
          fi

      - name: run tests
        shell: bash
        run: |
          go test ./... --race
